/*
 * Copyright 2015 Red Hat, Inc. and/or its affiliates.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
*/

package org.example;
import org.example.System;

query "Aggregates"
	$conclusion : Aggregate()
end

rule "will execute per each Bot 1 and Bot 2 operated"
no-loop
when
	Bot( id == "1", executed == true )
	Bot( id == "2", executed == true )
then
	System s = new System("A",true);
	insert(s);
end

rule "will execute per each Bot 3 operated and Bot 4 not operated"
no-loop
when
	Bot( id == "3", executed == true ) or
	Bot( id == "4", executed == false )
then
	System s = new System("B",true);
	insert(s);
end

rule "will execute per each Bot 5 operated and Bot 6 not operated"
no-loop
when
	Bot( id == "5", executed == true )
	Bot( id == "6", executed == false )
then
	System s = new System("C",true);
	insert(s);
end

rule "will execute per each Bot 7 and Bot 8 operated"
no-loop
when
	Bot( id == "7", executed == true ) or
	Bot( id == "8", executed == true )
then
	System s = new System("D",true);
	insert(s);
end

rule "will execute per each System A and System B active"
no-loop
when
	System( id == "A", active == true )
	System( id == "B", active == true )
then
	Aggregate a = new Aggregate("AB",true);
	insert(a);
end

rule "will execute per each System C and System D active"
no-loop
when
	System ( id == "C", active == true )
	System( id == "D", active == true )
then
	Aggregate a = new Aggregate("CD",true);
	insert(a);
end